### ISSUE TITLE
Crash on opening code ui

### ISSUE THREAD

**Issue by noukhern** [Lyinginbedmon/TricksyFoxes#1]
Using only Component API, fabric api and TricksyFoxes. The ui opens up for a moment after using a scroll on a fox, but then crashes.

[crash-2023-11-01_18.20.25-server.txt](https://github.com/Lyinginbedmon/TricksyFoxes/files/13229939/crash-2023-11-01_18.20.25-server.txt)

**Comment by noukhern** [comment]
After building the mod from the source it seems to work fine there, and 1.6 changelog indicates a similar bug got fixed, coult it be that modrinth has a previous version from the one that's specified?

**Comment by Lyinginbedmon** [comment]
It seems to be an unrelated bug, most likely a consequence of using an identical method in the ITricksyMob interface to one in LivingEntity that was then obfuscated differently. I've addressed the problem for the next version.

**Comment by noukhern** [comment]
Thank you, I found another crash while trying to fix this one, but it might be better if I hold on opening another issue until you have released that new version.
