### ISSUE TITLE
Fox doesent convert

### ISSUE THREAD

**Issue by sirben99** [Lyinginbedmon/TricksyFoxes#2]
Hey!

Im not sure if im doing something wrong, but i gave a fox the Periapt O Prescience and nothing is happening. I tried to look in the wiki but i dint find anything useful. I did see in the mod page that i have to take the fox to an dimensional trip, so do i have to take him to Nether and End? Im very lost how to start with the mod, using tricksy-1.8

**Comment by Lyinginbedmon** [comment]
Yes, the fox needs to visit the Nether and then the Overworld. This information only starts to be tracked once the fox receives the periapt, essentially serving as the starting point for their journey to enlightenment. I'll add a page to the wiki to make the process a bit clearer.

**Comment by sirben99** [comment]
Hey!

Sorry for super late response. Im still having huge amount of problems accually converting my fox. Im using Tricksy 3.6 version with Fabric 1.20.1, and no matter what i do the fox doesent convert at all. I have bringed the fox to the Nether and back to the Overworld multiple times, but nothing is happening.
How exacly is the fox supposed to be visiting the Nether and Overworld? I tried to push it through the Nether portal, but no luck

**Comment by Lyinginbedmon** [comment]
The default process is to right-click a fox with a periapt, then get them into the Nether and then to the Overworld via a portal. If it worked, there should be a sound effect followed by particles when both prerequisites are achieved. If problems persist, I suggest either using the /tricksy command to review the fox's accomplishments and potentially to forcibly enlighten them. Otherwise, please see if release 4.0 resolves the issue.

**Comment by sirben99** [comment]
I tested the command, and it says that im missing Visit Overworld. It did found Visit Nether however, but for whatever reason it doesent want to count the Overworld one.

Im playing in a modpack, so im not sure when the next update is. I am also playing on a server, if that matters.
Ill try to forcefully convert the fox with a command if nothing else works

**Comment by Lyinginbedmon** [comment]
The /tricksy accomplishments command can forcibly grant an accomplishment if, for whatever reason, it failed to unlock properly. I'm not sure how that can happen if the Nether accomplishment unlocked properly, but it may be due to the modpack context.

**Comment by sirben99** [comment]
The forceful conversion worked. But now it throws me out of the server every time i right click the fox. The server log logged an error.

Error: https://pastebin.com/LwEGWaj1

**Comment by Lyinginbedmon** [comment]
That is a known bug that was fixed in release 4.0, it only occurs in multiplayer which unfortunately I didn't get as many bug reports for
