### ISSUE TITLE
Mod incompat: Roughly Enough Items GUI renders over Tricksy Editor (1.20.1)

### ISSUE THREAD

**Issue by kbsmilk** [Lyinginbedmon/TricksyFoxes#4]
Repro:
1. Install Tricksy Foxes, REI, and their dependencies into a new instance, with default settings
2. Open the Tricksy editor.

It's easy to workaround with the 'toggle REI' hotkey; only a bit tedious.

P.S. this mod looks very nicely executed, and I love the detailed wiki. Excited to see what I can do with it. I just installed it!

![explorer_kbksW20pJ6](https://github.com/Lyinginbedmon/TricksyFoxes/assets/40084056/96fa48fb-f818-4ec2-bb09-fefee138ef40)

![javaw_Pp4UzjkXcx](https://github.com/Lyinginbedmon/TricksyFoxes/assets/40084056/055b37cb-07cc-4e47-a618-421707bb7c37)

**Comment by Lyinginbedmon** [comment]
This certainly does make it rather difficult to use the editor as intended. I've implemented a compatibility plugin for the next version, testing shows promise that this issues has been resolved. Thanks for the report and hope you enjoy the foxes and goats!
