### ISSUE TITLE
Unregistered `ScreenHandlerType`s

### ISSUE THREAD

**Issue by EnderTurret** [Lyinginbedmon/TricksyFoxes#8]
Basically, Tricksy Foxes's `ScreenHandlerType`s aren't registered, which leads to a disconnection from dedicated servers when any of the mod's container screens are opened (or at least, the tricksy creature inventory one).

I'm running v3.4 through Connector, but from some code analysis I believe the issue is still present in the current dev version, and I'd be surprised if Connector is throwing out random registry entries.

Currently, I'm using the following mixin which appears to fix the issue:

```java
@Mixin(TricksyFoxes.class)
public abstract class MixinTricksyFoxes {

	@Inject(at = @At("TAIL"), method = "onInitialize", remap = false)
	private void initializeMenuTypes(CallbackInfo ci) {
		TFScreenHandlerTypes.init();
	}
}
```

### Steps to reproduce

1. Have a client and dedicated server both running Tricksy Foxes
2. Connect to the server
3. Obtain a tricksy fox (or probably any other tricksy creature)
4. Try to open their inventory

**Comment by Lyinginbedmon** [comment]
Ah this seems to be the root of an earlier-reported bug! I wasn't able to reproduce it but this does indeed seem to be what's up. Thanks for the report!
