### ISSUE TITLE
Escape should not close the whiteboard

### ISSUE THREAD

**Issue by Luke100000** [Lyinginbedmon/TricksyFoxes#9]
Hi, great mod!

I keep closing the gui without saving because I hit escape when in the whiteboard. This is inconsistent with closing nodes with escape.

It would be great if escape returns to the main menu instead.

**Comment by Lyinginbedmon** [comment]
Changes to the whiteboard are not saved on escape to prevent the accidental deletion of values. This is actually consistent with the node view, where changes made to the behaviour tree are not saved until the Save button is actually pressed. Escape is the intended way to exit the editor without saving your changes.

**Comment by Luke100000** [comment]
Yes, but when you hit escape in a nodes field settings, you return to the node. If you hit escape in a node you return to the main screen. Thus I can always use escape to go one step back.

If I hit escape in the whiteboard, it immediately closes the screen, instead of going back.

I would expect having to hit escape twice when in the whiteboard: once to get back to main, then another time to actually close the screen.
